// ============================================================
// DevOS — Autonomous AI Execution System
// Copyright (c) 2026 Shiva Deore. All rights reserved.
// ============================================================

// research/insightSynthesizer.ts — Synthesise insights from scored sources

import { llmCall }      from "../llm/router";
import { ScoredResult } from "./relevanceScorer";
import { FetchResult }  from "../web/pageFetcher";

export interface SourceDoc {
  scored:   ScoredResult;
  fetched?: FetchResult;
}

export interface Insight {
  point:    string;
  source?:  string;
}

export interface SynthesisResult {
  insights:  Insight[];
  summary:   string;
  sources:   string[];
  rawReport: string;
}

export class InsightSynthesizer {

  async synthesize(goal: string, docs: SourceDoc[]): Promise<SynthesisResult> {
    // ── Filter to relevant, successfully fetched docs ──────
    const usable = docs
      .filter(d => d.scored.score > 0 && d.fetched?.success)
      .slice(0, 6);

    if (usable.length === 0) {
      console.warn("[InsightSynthesizer] No usable documents — returning minimal result");
      return {
        insights:  [{ point: "No relevant web sources found for this goal." }],
        summary:   "Research yielded no usable results.",
        sources:   [],
        rawReport: "",
      };
    }

    // ── Build context for LLM ─────────────────────────────
    const context = usable
      .map((d, i) => {
        const text = d.fetched!.text?.slice(0, 600) ?? d.scored.snippet;
        return `SOURCE ${i + 1}: ${d.scored.title}\nURL: ${d.scored.url}\n${text}`;
      })
      .join("\n\n---\n\n");

    const prompt = `You are a research assistant. Based on the sources below, extract 3–5 key insights relevant to the goal: "${goal}".

SOURCES:
${context}

Respond with ONLY a JSON object in this exact format:
{
  "insights": [
    { "point": "key finding", "source": "url or title" }
  ],
  "summary": "2–3 sentence executive summary"
}`;

    try {
      const { content } = await llmCall(prompt, "You are a research analyst that extracts structured insights from web content.");
      const cleaned = content.replace(/```json|```/g, "").trim();
      const parsed  = JSON.parse(cleaned);

      const insights: Insight[] = (parsed.insights ?? []).map((i: any) => ({
        point:  String(i.point ?? ""),
        source: i.source ? String(i.source) : undefined,
      }));

      const summary = String(parsed.summary ?? "");
      const sources = usable.map(d => d.scored.url);

      return {
        insights,
        summary,
        sources,
        rawReport: this.toReport(goal, insights, summary, sources),
      };

    } catch (err: any) {
      console.error(`[InsightSynthesizer] LLM parse error: ${err.message}`);

      // Fallback: use snippets directly
      const insights: Insight[] = usable.map(d => ({
        point:  d.scored.snippet || d.scored.title,
        source: d.scored.url,
      }));
      const summary = `Research on "${goal}" found ${usable.length} relevant sources.`;
      const sources = usable.map(d => d.scored.url);

      return {
        insights,
        summary,
        sources,
        rawReport: this.toReport(goal, insights, summary, sources),
      };
    }
  }

  toReport(goal: string, insights: Insight[], summary: string, sources: string[]): string {
    const now = new Date().toISOString().replace("T", " ").slice(0, 19);
    const lines: string[] = [
      `# Research Report: ${goal}`,
      `*Generated by DevOS — ${now}*`,
      "",
      "## Executive Summary",
      "",
      summary,
      "",
      "## Key Insights",
      "",
    ];

    insights.forEach((ins, i) => {
      lines.push(`${i + 1}. ${ins.point}`);
      if (ins.source) lines.push(`   Source: ${ins.source}`);
    });

    lines.push("", "## Sources", "");
    sources.forEach((s, i) => lines.push(`${i + 1}. ${s}`));

    return lines.join("\n");
  }
}

export const insightSynthesizer = new InsightSynthesizer();
