name               = "devos-license-server"
main               = "license-server.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "LICENSES"
id      = "2b5817ca66ed4bcb8114452d48afd38f"

[[kv_namespaces]]
binding = "REGISTRATIONS"
id      = "ab2c47fbbaf94c6ba9778effb7177891"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "api.taracod.com"
custom_domain = true


