// ============================================================
// DevOS — Autonomous AI Execution System
// Copyright (c) 2026 Shiva Deore. All rights reserved.
// ============================================================

// core/microPlanners/researchTopic.ts — Web research and synthesis plan

import { ParsedGoal } from "../goalParser"

export class ResearchTopicPlanner {

  canHandle(g: ParsedGoal): boolean {
    const rawLower = g.raw.toLowerCase()
    return g.type === "research" ||
           g.domain === "data" ||
           /\b(research|analyze|analyse|find|summarize|investigate|report on)\b/.test(rawLower)
  }

  buildPlan(g: ParsedGoal): any {
    const topic = g.raw
      .toLowerCase()
      .replace(/^(research|analyze|find|summarize|investigate|report on)\s+/i, "")
      .replace(/[^a-z0-9_-]/g, "_")
      .slice(0, 40) || "research"

    const reportFile = `research_${topic}.md`

    return {
      summary:    `Research: ${g.raw.slice(0, 80)}`,
      complexity: "medium",
      actions: [
        {
          type:        "llm_task",
          description: "Generate focused research questions from the goal",
          query: `Generate exactly 5 concise research questions for the following goal:
"${g.raw}"
Return them as a numbered list. Focus on actionable, specific questions.`,
          risk:        "low",
        },
        {
          type:        "web_search",
          description: "Search the web for current information on the topic",
          query:       g.raw,
          risk:        "low",
        },
        {
          type:        "llm_task",
          description: "Synthesise web findings into a structured research summary",
          query: `Synthesise the following research about "${g.raw}" into a clear, structured markdown report.
Include: Executive Summary, Key Findings, Analysis, Recommendations, Sources.`,
          risk:        "low",
        },
        {
          type:        "file_write",
          description: `Save research report to ${reportFile}`,
          path:        reportFile,
          content: `# Research Report: ${g.raw}

*Generated by DevOS on ${new Date().toISOString().split("T")[0]}*

## Executive Summary
[LLM synthesis will populate this section]

## Key Findings
- Finding 1
- Finding 2
- Finding 3

## Analysis
[Detailed analysis goes here]

## Recommendations
[Action items based on research]

## Sources
- Web search results
`,
          risk:        "low",
        },
      ],
      _source: "micro-planner:researchTopic",
    }
  }
}

export const researchTopicPlanner = new ResearchTopicPlanner()
