// scripts/inject-version.js
// Reads version from package.json and writes core/version.ts.
// Run automatically via prebuild:api / prebuild:cli npm hooks.
'use strict'
const fs   = require('fs')
const path = require('path')
const ROOT = path.join(__dirname, '..')
const pkg  = JSON.parse(fs.readFileSync(path.join(ROOT, 'package.json'), 'utf-8'))
const out  = `// AUTO-GENERATED by scripts/inject-version.js — do not edit by hand\nexport const VERSION = '${pkg.version}'\n`
fs.writeFileSync(path.join(ROOT, 'core', 'version.ts'), out, 'utf-8')
console.log(`[inject-version] core/version.ts → '${pkg.version}'`)
